### ISSUE TITLE
Parse maze files

### ISSUE THREAD

**Issue by Penchant** [Penchant/Maze-Search#8]
Functionality for parsing maze files is necessary

**Comment by Penchant** [comment]
Maze key: 
- Food pellet: "*" 
- Wall: "%" 
- Starting point: "P"

**Comment by btrent5** [comment]
creating node class to hold connections with precalculated distance to speed things up?

**Comment by btrent5** [comment]
importMaze returns a 2d array of nodes, each with north, east, south, west connections and manhattan distance to goal
